apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask

spec:
  replicas: 3

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      imagePullSecrets:
         - name: ecr-secret

      containers:
        - name: flask
          image: 148908330969.dkr.ecr.ap-south-1.amazonaws.com/cloud-native-task-manager:13

          ports:
            - containerPort: 5000

          env:
            - name: DATABASE_URL
              value: postgresql://task_user:password@postgres:5432/task_manager

            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DATABASE_HOST

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DATABASE_PORT

            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: DATABASE_NAME
